// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using task_01_ef_core_modeling_drills.Data;

#nullable disable

namespace task_01_ef_core_modeling_drills.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260914215708_changeseeddata")]
    partial class changeseeddata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("task_01_ef_core_modeling_drills.Models.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("FinalGrade")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingTrackId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("TrainingTrackId");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EnrollmentDate = new DateTime(2026, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            StudentId = 1,
                            TrainingTrackId = 1
                        },
                        new
                        {
                            Id = 2,
                            EnrollmentDate = new DateTime(2026, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinalGrade = 90m,
                            Status = 1,
                            StudentId = 1,
                            TrainingTrackId = 2
                        },
                        new
                        {
                            Id = 3,
                            EnrollmentDate = new DateTime(2026, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            StudentId = 2,
                            TrainingTrackId = 2
                        },
                        new
                        {
                            Id = 4,
                            EnrollmentDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinalGrade = 95m,
                            Status = 1,
                            StudentId = 3,
                            TrainingTrackId = 3
                        },
                        new
                        {
                            Id = 5,
                            EnrollmentDate = new DateTime(2026, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            StudentId = 4,
                            TrainingTrackId = 1
                        });
                });

            modelBuilder.Entity("task_01_ef_core_modeling_drills.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "mohamed@gmail.com",
                            Name = "Mohammed ahmed",
                            PhoneNumber = "01087655678"
                        },
                        new
                        {
                            Id = 2,
                            Email = "sara.hassan@gmail.com",
                            Name = "Sara Hassan",
                            PhoneNumber = "01123456789"
                        });
                });

            modelBuilder.Entity("task_01_ef_core_modeling_drills.Models.PaymentSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<decimal>("RemainingAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalRequired")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentId")
                        .IsUnique();

                    b.ToTable("PaymentSummaries");
                });

            modelBuilder.Entity("task_01_ef_core_modeling_drills.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Sonds@gmail.com",
                            FullName = "Sondos waheed",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "omar.ali@gmail.com",
                            FullName = "Omar Ali",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nour.m@gmail.com",
                            FullName = "Nour Mahmoud",
                            IsActive = true,
                            IsDeleted = true
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "youssef.i@gmail.com",
                            FullName = "Youssef Ibrahim",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mariam.k@gmail.com",
                            FullName = "Mariam Khaled",
                            IsActive = false,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("task_01_ef_core_modeling_drills.Models.StudentProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("EmergencyPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("StudentProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "21 sreet",
                            DateOfBirth = new DateOnly(2005, 4, 18),
                            EmergencyPhone = "01063500543",
                            NationalId = "98464748493033",
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "Nasr City, Cairo",
                            DateOfBirth = new DateOnly(1999, 1, 1),
                            EmergencyPhone = "01011112222",
                            NationalId = "29901011234567",
                            StudentId = 2
                        },
                        new
                        {
                            Id = 3,
                            Address = "Maadi, Cairo",
                            DateOfBirth = new DateOnly(2001, 5, 5),
                            EmergencyPhone = "01033334444",
                            NationalId = "30105051234568",
                            StudentId = 3
                        },
                        new
                        {
                            Id = 4,
                            Address = "Giza",
                            DateOfBirth = new DateOnly(1998, 11, 11),
                            EmergencyPhone = "01055556666",
                            NationalId = "29811111234569",
                            StudentId = 4
                        },
                        new
                        {
                            Id = 5,
                            Address = "Alexandria",
                            DateOfBirth = new DateOnly(2002, 3, 3),
                            EmergencyPhone = "01077778888",
                            NationalId = "30203031234570",
                            StudentId = 5
                        });
                });

            modelBuilder.Entity("task_01_ef_core_modeling_drills.Models.TrainingTrack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.ToTable("TrainingTracks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InstructorId = 1,
                            Title = "Frontend"
                        },
                        new
                        {
                            Id = 2,
                            InstructorId = 1,
                            Title = "Backend"
                        },
                        new
                        {
                            Id = 3,
                            InstructorId = 2,
                            Title = "UI/UX Design"
                        });
                });

            modelBuilder.Entity("task_01_ef_core_modeling_drills.Models.Enrollment", b =>
                {
                    b.HasOne("task_01_ef_core_modeling_drills.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("task_01_ef_core_modeling_drills.Models.TrainingTrack", "TrainingTrack")
                        .WithMany("Enrollments")
                        .HasForeignKey("TrainingTrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("TrainingTrack");
                });

            modelBuilder.Entity("task_01_ef_core_modeling_drills.Models.PaymentSummary", b =>
                {
                    b.HasOne("task_01_ef_core_modeling_drills.Models.Enrollment", "Enrollment")
                        .WithOne("PaymentSummary")
                        .HasForeignKey("task_01_ef_core_modeling_drills.Models.PaymentSummary", "EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("task_01_ef_core_modeling_drills.Models.StudentProfile", b =>
                {
                    b.HasOne("task_01_ef_core_modeling_drills.Models.Student", "student")
                        .WithOne("studentProfile")
                        .HasForeignKey("task_01_ef_core_modeling_drills.Models.StudentProfile", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("student");
                });

            modelBuilder.Entity("task_01_ef_core_modeling_drills.Models.TrainingTrack", b =>
                {
                    b.HasOne("task_01_ef_core_modeling_drills.Models.Instructor", "Instructor")
                        .WithMany("TrainingTracks")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("task_01_ef_core_modeling_drills.Models.Enrollment", b =>
                {
                    b.Navigation("PaymentSummary")
                        .IsRequired();
                });

            modelBuilder.Entity("task_01_ef_core_modeling_drills.Models.Instructor", b =>
                {
                    b.Navigation("TrainingTracks");
                });

            modelBuilder.Entity("task_01_ef_core_modeling_drills.Models.Student", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("studentProfile")
                        .IsRequired();
                });

            modelBuilder.Entity("task_01_ef_core_modeling_drills.Models.TrainingTrack", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
